### ISSUE TITLE
Basic view for landing page

### ISSUE THREAD

**Issue by armyofbear136** [zachandthefriedmen/GraceShopper#11]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

*Issue description here…*

As a User, I want to be greeted with a friendly landing page that easily routes me to products and purchasing options, so I have a pleasant hassle-free experience purchasing pet supplies.

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Landing Page layout](https://trello.com/c/mZy0ZSkH/29-create-landing-page-layout)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhance/Stylize Landing Page](https://trello.com/c/BOAkwygt/30-enhance-stylize-landing-page)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing page basic CSS](https://trello.com/c/0hvTNrVb/43-landing-page-basic-css)
