### ISSUE TITLE
Basic Navbar

### ISSUE THREAD

**Issue by mjthor86** [zachandthefriedmen/GraceShopper#15]
As a user, I want to be able to view a navigation bar at all times so that I can easily move between different views.

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Navbar DESIGN](https://trello.com/c/0jBVr2eg/32-navbar-design)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Navbar component](https://trello.com/c/1gAoDwmd/33-navbar-component)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Navbar basic CSS](https://trello.com/c/nGx2DThL/44-navbar-basic-css)
