### ISSUE TITLE
Basic view for all products

### ISSUE THREAD

**Issue by mjthor86** [zachandthefriedmen/GraceShopper#3]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

*Issue description here…*

As a user, I want to be able to view all products so that I can purchase what I want/need immediately

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Define product database model](https://trello.com/c/vaHtZSGf/12-define-product-database-model)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Define order database model](https://trello.com/c/GNhTy5YB/13-define-order-database-model)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Product reducer](https://trello.com/c/faVVQwBW/16-product-reducer)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create All Products View](https://trello.com/c/8BdSucmo/25-create-all-products-view)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Products reducer tests](https://trello.com/c/RU5vTJpY/39-products-reducer-tests)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [category reducer](https://trello.com/c/yWEpdENl/41-category-reducer)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [All products basic CSS](https://trello.com/c/xSD8Jt1Q/46-all-products-basic-css)
