### ISSUE TITLE
Basic view for account management page

### ISSUE THREAD

**Issue by Semiroundpizza8** [zachandthefriedmen/GraceShopper#33]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

As a user, I want to be able to see my current account information and edit it from the browser, allowing me to change fields such as my name, password, address(es?), and google/facebook connections.

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Account Management WIREFRAME](https://trello.com/c/70pl4sz6/51-account-management-wireframe)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Account Management Component](https://trello.com/c/9xK29BzQ/52-account-management-component)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Account Management CSS](https://trello.com/c/RY2eaTuK/53-account-management-css)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Account page: fill in dummy data with dynamic data from store](https://trello.com/c/eOjv2zoL/78-account-page-fill-in-dummy-data-with-dynamic-data-from-store)
