### ISSUE TITLE
Sorting for All Products

### ISSUE THREAD

**Issue by Semiroundpizza8** [zachandthefriedmen/GraceShopper#38]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

As a user, I want to refine product listings by category, so that I can narrow down my choices to see only the types of items I'm interested in.

As a user, I want to search product listings, so that I can find specific products I want by name.

**Comment by ZacharyDudley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AllProducts - view by category](https://trello.com/c/ZrjSkj2a/56-allproducts-view-by-category)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AllProducts - view by category](https://trello.com/c/ZrjSkj2a/56-allproducts-view-by-category)

**Comment by ZacharyDudley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AllProducts - view by name](https://trello.com/c/z5Ta5G1z/57-allproducts-view-by-name)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AllProducts - view by name](https://trello.com/c/z5Ta5G1z/57-allproducts-view-by-name)
