### ISSUE TITLE
Update cart with userId upon login

### ISSUE THREAD

**Issue by matthew-thor** [zachandthefriedmen/GraceShopper#41]
- As an admin,
- I want an unauthenticated cart to have a user ID added to it when a user logs in
- so that I can better keep track of user's purchases and interests and sell that data for $$$

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX: make join table for orders and items](https://trello.com/c/YreqDVTI/61-fix-make-join-table-for-orders-and-items)

**Comment by armyofbear136** [comment]
I believe this is working
