### ISSUE TITLE
View user orders

### ISSUE THREAD

**Issue by matthew-thor** [zachandthefriedmen/GraceShopper#45]
- As a logged in user
- view my list of previous orders,
- so that I can find and individual order I made in the past and review it

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Order by user route](https://trello.com/c/Ah9dHo0M/60-order-by-user-route)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX: make join table for orders and items](https://trello.com/c/YreqDVTI/61-fix-make-join-table-for-orders-and-items)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX: update seed file](https://trello.com/c/ooaFEL9z/63-fix-update-seed-file)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX: order model (remove 'items' property and fix getter methods)](https://trello.com/c/xO3fqraJ/62-fix-order-model-remove-items-property-and-fix-getter-methods)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [?? add api routes for new order-product table ??](https://trello.com/c/4GAzkMRm/64-add-api-routes-for-new-order-product-table)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [update seed with OrderProducts and correct associatons](https://trello.com/c/0FfQuemK/65-update-seed-with-orderproducts-and-correct-associatons)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix: build order with products join table info WITH full product info being loaded in](https://trello.com/c/qNZVWT2r/66-fix-build-order-with-products-join-table-info-with-full-product-info-being-loaded-in)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [cleaning up user account page](https://trello.com/c/bjN5CCEg/99-cleaning-up-user-account-page)
