### ISSUE TITLE
Cart Editing

### ISSUE THREAD

**Issue by ZacharyDudley** [zachandthefriedmen/GraceShopper#50]
As a User, I want to add items to my cart from the product listing or product detail pages, so that I can purchase them later.

As a User, I want to remove items from my cart, in case I decide I don't want an item anymore.

As a User, I want to edit/remove quantities of items in the cart, in case I decide I want more or less of a particular item.

**Comment by ZacharyDudley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cart - Editing](https://trello.com/c/l8N5wzf3/67-cart-editing)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [reducer/route for removing products from cart](https://trello.com/c/XN4Moyz1/90-reducer-route-for-removing-products-from-cart)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fill in cart data on component with information from store](https://trello.com/c/UZCJlMOS/94-fill-in-cart-data-on-component-with-information-from-store)
