### ISSUE TITLE
Logged in user reviews

### ISSUE THREAD

**Issue by ZacharyDudley** [zachandthefriedmen/GraceShopper#66]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---
As an authenticated user, I want to be able to leave reviews on products I've bought so I can let other users know my opinion of the product.

**Comment by ZacharyDudley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Single Product - leave a review](https://trello.com/c/mF9RPCa3/79-single-product-leave-a-review)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add ability to create reviews on single product page](https://trello.com/c/k9LCY2uE/98-add-ability-to-create-reviews-on-single-product-page)
