### ISSUE TITLE
Create Admin page

### ISSUE THREAD

**Issue by ZacharyDudley** [zachandthefriedmen/GraceShopper#67]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

As an admin, I want a page where I can administrate.

**Comment by ZacharyDudley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Admin Page](https://trello.com/c/NDcnHDdf/80-create-admin-page)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Admin User View](https://trello.com/c/FZWoRCW7/81-create-admin-user-view)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Admin Product View](https://trello.com/c/ZEaFoIxK/82-create-admin-product-view)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Admin Category View](https://trello.com/c/DcepjZbD/83-create-admin-category-view)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Admin Order View](https://trello.com/c/ynrLn5jp/84-create-admin-order-view)
