### ISSUE TITLE
View only available products

### ISSUE THREAD

**Issue by ZacharyDudley** [zachandthefriedmen/GraceShopper#74]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

As a user, I want to only see available products on the all product page.

If a product is no longer available, users will not see it while browsing, but they can view the product detail page if they've ordered it previously or have a direct link. On that product detail page, it should say "Currently Unavailable"

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Products/Single Products  - Unavailable products won't appear when browsing the site](https://trello.com/c/QY7crezT/91-products-single-products-unavailable-products-wont-appear-when-browsing-the-site)
