### ISSUE TITLE
Navigating from singleProduct to allProdcuts bug

### ISSUE THREAD

**Issue by Semiroundpizza8** [zachandthefriedmen/GraceShopper#78]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---
As a user, I want to be able to move from the single products page to the all products page without the site crashing.

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Able to navigate from singleProducts to allProducts without issue](https://trello.com/c/kYMoagT1/93-able-to-navigate-from-singleproducts-to-allproducts-without-issue)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Checkout email](https://trello.com/c/mpSJG2ty/100-checkout-email)
