### ISSUE TITLE
View basic info on single product page

### ISSUE THREAD

**Issue by Semiroundpizza8** [zachandthefriedmen/GraceShopper#8]
As a user, I want to be able to view the image, title and details of a single product so that I can decide whether or not I want to buy it.

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Single product (details) component](https://trello.com/c/n115xzLk/26-single-product-details-component)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Single product reducer](https://trello.com/c/6NLah8gJ/31-single-product-reducer)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [reviews reducer](https://trello.com/c/xIpevN8F/38-reviews-reducer)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Single product basic CSS](https://trello.com/c/Ryl33iUY/47-single-product-basic-css)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Footer basic CSS](https://trello.com/c/LQVE3EHG/48-footer-basic-css)
