### ISSUE TITLE
Basic view for cart

### ISSUE THREAD

**Issue by Semiroundpizza8** [zachandthefriedmen/GraceShopper#9]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a user, I want a notification badge showing unread count, so I can easily manage my messages"
* "As a developer, I want linting to work properly with JSX, so I can see when there is a mistake"
* "As an admin, I want a management panel for users, so I can delete spurious accounts"

---

As a user, I want to be able to view the products and total price of my shopping cart so that I can decide whether or not I want to make that purchase.

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Cart View](https://trello.com/c/hlUue4aI/27-create-cart-view)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Single Product View](https://trello.com/c/n115xzLk/26-create-single-product-view)

**Comment by mjthor86** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cart component](https://trello.com/c/hlUue4aI/27-cart-component)

**Comment by armyofbear136** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [order reducer](https://trello.com/c/cRorThF7/37-order-reducer)

**Comment by Semiroundpizza8** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cart basic CSS](https://trello.com/c/qrJsvOIM/45-cart-basic-css)
